const pick=(o,ps)=>{for(const p of ps){let v=o;for(const k of p.split('.'))v=v?.[k];if(v!==undefined&&v!==null&&v!=='')return v}};
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const team=(m,s)=>String(pick(m,[`${s}_team`,`${s}Team.name`,`${s}.name`,s==='home'?'homeParticipant.name':'awayParticipant.name'])||'Ukendt hold');
const score=(m,s)=>num(pick(m,[`${s}_score`,`${s}Score`,`score.${s}`,s==='home'?'homeParticipant.score':'awayParticipant.score']));
const sides=m=>({h:String(pick(m,['home_team','homeTeam.name','home.name','homeParticipant.name'])||'').toLowerCase(),a:String(pick(m,['away_team','awayTeam.name','away.name','awayParticipant.name'])||'').toLowerCase()});
const gf=(m,t)=>{const x=sides(m),h=score(m,'home'),a=score(m,'away'),q=t.toLowerCase();if(h===null||a===null)return null;if(x.h===q||x.h.includes(q)||q.includes(x.h))return h;if(x.a===q||x.a.includes(q)||q.includes(x.a))return a;return null};
const total=m=>{const h=score(m,'home'),a=score(m,'away');return h===null||a===null?null:h+a};
const list=(m,ps)=>{const x=pick(m,ps);return Array.isArray(x)?x:[]};
const history=(m,s)=>list(m,s==='home'?['home_history','homeHistory','homeTeamHistory','history.home','recentMatches.home']:['away_history','awayHistory','awayTeamHistory','history.away','recentMatches.away']);
const h2h=m=>list(m,['h2h','headToHead','head_to_head','history.h2h','mutualH2H']);
const rate=(xs,p)=>xs.length?xs.filter(p).length/xs.length:null, clamp=x=>Math.max(0,Math.min(1,x));
export function evaluate(m,c){const home=team(m,'home'),away=team(m,'away'),hh=history(m,'home'),ah=history(m,'away'),duels=h2h(m),h5=hh.slice(0,5),a5=ah.slice(0,5);const hg=hh.map(x=>gf(x,home)).filter(x=>x!==null).slice(0,c.lookback),ag=ah.map(x=>gf(x,away)).filter(x=>x!==null).slice(0,c.lookback),dt=duels.map(total).filter(x=>x!==null),ht=h5.map(total).filter(x=>x!==null),at=a5.map(total).filter(x=>x!==null);if(!hg.length||!ag.length||h5.length<5||a5.length<5||!dt.length)return{home,away,status:'missing'};const homeAvg=hg.reduce((a,b)=>a+b)/hg.length,awayAvg=ag.reduce((a,b)=>a+b)/ag.length,hScored=h5.filter(x=>gf(x,home)>=1).length,aScored=a5.filter(x=>gf(x,away)>=1).length,h2hOver15=rate(dt,x=>x>1.5),homeOver15=rate(ht,x=>x>1.5),awayOver15=rate(at,x=>x>1.5),recentBtts=rate([...h5,...a5],x=>score(x,'home')>=1&&score(x,'away')>=1);const criteria=[homeAvg>c.minAvg&&awayAvg>c.minAvg,h2hOver15>c.minH2H,hScored>=c.minScored&&aScored>=c.minScored,homeOver15>=c.minOver15&&awayOver15>=c.minOver15,recentBtts>=c.minBtts];const index=100*(.25*clamp(((homeAvg+awayAvg)/2-1)/1.5)+.20*h2hOver15+.20*(hScored+aScored)/10+.20*(homeOver15+awayOver15)/2+.15*recentBtts);return{home,away,league:String(pick(m,['league','competition.name','tournament.name'])||''),kickoff:String(pick(m,['start_time','startTime','kickoff','time'])||''),status:'ok',passed:criteria.every(Boolean),criteria,score:+index.toFixed(1),metrics:{homeAvg,awayAvg,hScored,aScored,h2hOver15,h2hN:dt.length,homeOver15,awayOver15,recentBtts}}}
export function rank(ms,c){const all=ms.map(x=>evaluate(x,c));return{results:all.filter(x=>x.status==='ok').sort((a,b)=>Number(b.passed)-Number(a.passed)||b.score-a.score),missing:all.filter(x=>x.status==='missing').length}}
